server:
  port: 8080
spring:
  application:
    name: demo
  datasource:
    url: jdbc:h2:mem:testdb;
    username: sa
    password: 
    driver-class-name: org.h2.Driver
#    data: classpath:data-h2.sql
    hikari:
      minimum-idle: 1
      maximum-pool-size: 5
  h2:
    console:
      enabled: true
      path: /h2
logging:
  level:
    org.usf.jquery: DEBUG
    org.springframework.jdbc.core: DEBUG